name: diplomovka
description: "Diplomovka"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  video_player: ^2.3.0
  flutter_xlider: ^3.5.0
  syncfusion_flutter_gauges: ^26.2.10
  flutter_datetime_picker: ^1.5.1
  month_year_picker: ^0.4.0+1
  intl: ^0.19.0
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  fluttertoast: ^8.2.8
  google_sign_in: ^6.2.1
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  flutter_slidable: ^3.1.2
  flutter_secure_storage: 9.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images_videos/
    - lib/assets/icons/

